arch = [
    "base-devel",
    "base",
    "bat",
    "bc",
    "cronie",
    "efibootmgr",
    "fzf",
    "git-crypt",
    "git",
    "grub",
    "iwd",
    "jq",
    "less",
    "linux-firmware",
    "linux-headers",
    "linux",
    "man-db",
    "man-pages",
    "metapac",
    "nano",
    "networkmanager",
    "pacman-contrib",
    "rcm",
    "socat",
    "sof-firmware",
    "tree",
    "ufw",
    "wireless_tools",
    "xdg-utils",
    "xorg-xhost",
    "yay-bin",
    "zram-generator",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "zsh",
]
