arch = [
    "chromium",
    "cmatrix",
    "dbeaver",
    "discord",
    "file-roller",
    "firefox",
    "font-manager",
    "github-desktop-bin",
    "gnome-calculator",
    "gnome-calendar",
    "gnome-disk-utility",
    "gnome-tweaks",
    "gufw",
    "imagemagick",
    "jd-gui-bin",
    "libreoffice-fresh",
    "loupe",
    "lxappearance",
    "mission-center",
    "mongodb-compass",
    "nemo-fileroller",
    "nemo",
    "neofetch",
    "netextender",
    "nmap",
    "nwg-look",
    "obs-studio",
    "pamixer",
    "pavucontrol",
    "pdfarranger",
    "pipes.sh",
    "postman-bin",
    "python-requests",
    "qpwgraph",
    "qt5ct",
    "qt6ct",
    "redisinsight-bin",
    "rnote",
    "rust",
    "safeeyes",
    "sassc",
    "seahorse",
    "teams-for-linux-bin",
    "todoist-appimage",
    "visual-studio-code-bin",
    "vlc",
    "zen-browser-avx2-bin",
]
