arch = [
    "dbeaver",
    "fnm-bin",
    "github-cli",
    "github-desktop-bin",
    "graphviz",
    "jd-gui-bin",
    "john",
    "mongodb-compass",
    "mvnd",
    "netextender",
    "postman-bin",
    "python-requests",
    "redisinsight-bin",
    "rsync",
]
