arch = [
    "bar-gmail",
    "bibata-cursor-theme-bin",
    "cliphist",
    "copyq",
    "gnome-keyring",
    "grim",
    "gtkmm",
    "gtkmm3",
    "hypridle",
    "hyprland",
    "hyprpaper",
    "hyprpicker",
    "hyprshot",
    "kvantum-qt5",
    "kvantum",
    "nwg-panel",
    "orchis-theme-git",
    "otf-font-awesome",
    "pipewire-pulse",
    "polkit-gnome",
    "polkit-qt5",
    "qt5-wayland",
    "qt6-wayland",
    "rofi-wayland",
    "rofimoji-git",
    "sddm",
    "slurp",
    "swaync",
    "terminator",
    "ttf-intel-one-mono",
    "ttf-nerd-fonts-symbols",
    "wev",
    "wireplumber",
    "wl-clipboard",
    "wlogout",
    "wlrctl",
    "wtype",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-hyprland",
    "yad",
    "ydotool",
]
